### ISSUE TITLE
No collision

### ISSUE THREAD

**Issue by CCIGAMES** [CCIGAMES/Rii-sports#4]
the collision wont work between the player and the map, we also need to get the player holding the object for the baseball level and make it hit the ball, perhaps modify the code of a sword for the bat and a bullet for the ball

**Comment by fgsoftware1** [comment]
this issue is already opened #3

**Comment by fgsoftware1** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [collision](https://trello.com/c/UnsOO2bz/7-collision)
